### ISSUE TITLE
Defining a global base template in oTree 5?

### ISSUE THREAD

**Issue by JKRhb** [oTree-org/oTree#100]
Hi! Is it currently possible to define a base template that is used as a basis by all pages in all apps? Just as in the project in this repo I have a  `_templates/global/Page.html` file in my project that includes global styles. Those, however, are not applied anymore after migrating to oTree 5.

Do I have to use a manual import statement in every template instead as it is implied by the documentation?

**Comment by oTree-org** [comment]
It still should work as before. You need to put {{ extends 'global/Page.html' }} at the top of your template. Let me know if that isn't working.

**Comment by JKRhb** [comment]
> 
> 
> It still should work as before. You need to put {{ extends 'global/Page.html' }} at the top of your template. Let me know if that isn't working.

Thank you, I think that was actually missing in the template of my app :)
