### ISSUE TITLE
Create session under "Sessions" tab does not delete older session links

### ISSUE THREAD

**Issue by powermukisa** [oTree-org/oTree#101]
Steps:
- On the sessions tab, create a new session for a game
- After the session is created, return to the sessions tab and Delete the session
- Create another session for the same game

Results:
- Older sessions are still shown under the `Single-use links` (see screeshot below)
- Session-wide link is not valid

Expected:
- Older sessions should be deleted
- Session wide link should be valid.

Note: does not happen when you archive instead of deleting a session.

![image_2021_06_21T06_30_08_874Z](https://user-images.githubusercontent.com/3297653/122719270-d2a9da80-d222-11eb-91fe-a2d3c92c202a.png)

**Comment by oTree-org** [comment]
Good find! I have found the cause (sqlite does not enforce FK constraints by default) and will publish a fix soon.
