### ISSUE TITLE
[feature request] allow oTree to be served under prefix

### ISSUE THREAD

**Issue by silently** [oTree-org/oTree#109]
Hello,

To my knowledge it is currently possible to serve oTree only at the root URL of a domain (like https://mydomain.com/). Indeed serving it under a subpath (or URL prefix) like https://mydomain.com/pathprefix is not possible due to oTree redirecting to https://mydomain.com/demo without the `pathprefix`.

Allowing this as an option (for instance in an environment variable, like `OTREE_WEB_PREFIX`) would be convenient. Known workaround is to use different subdomains but it's not always desirable or possible depending on the IT context.

Thanks!

**Comment by silently** [comment]
sorry I already posted this on otree-core I did not remember where it was:
https://github.com/oTree-org/otree-core/issues/570

**Comment by PhoenixAlx** [comment]
It's a good idea, hopefully!!
