### ISSUE TITLE
How to make choices random for each player?

### ISSUE THREAD

**Issue by aderiyeva** [oTree-org/oTree#112]
Hi!

I would really appreciate some hints about dynamic choices generation for surveys.
I have a big list of different course names. I would like to pick 4 random names from this list and present them as choices for each player (each player should have 4 different random names).  This should repeat for multiple pages and each time there should be a new set of names to pick from.

These were my attempts:

First I tried to use the `{field_name}_choices()` function
```
def coursestest_choices(player):
    loaded_dataset = loadDataSet(r'courses.xlsx')
    random_sets = generateSelection(loaded_dataset, 4)
    choices = []
    for set in random_sets:
        choice = [str(set["id"]), set["data"][0]] 
        choices.append(choice)
    return choices
```

This doesn't work and I get an 

> not a valid choice

 error.

My next attempt was to define multiple instances of the same field in the `Player` model and generate the random choices there:

```
class Player(BasePlayer):
    loaded_dataset = loadDataSet(r'courses.xlsx')

    random_sets = generateSelection(loaded_dataset, 4)
    testchoices = []
    for set in random_sets:
        choice = [str(set["id"]) , set["data"][0]] 
        testchoices.append(choice)
    coursestest1 = models.StringField(
        choices = choice_list,
        label='Bitte wählen Sie einen Kurs aus',
        widget=widgets.RadioSelect,
    )

    random_sets = generateSelection(loaded_dataset, 4)
    testchoices = []
    for set in random_sets:
        choice = [str(set["id"]), set["data"][0]] 
        testchoices.append(choice)
    coursestest2 = models.StringField(
        choices = testchoices,
        label='Bitte wählen Sie einen Kurs aus',
        widget=widgets.RadioSelect,
    )
```
This actually works but the randomly generated choices are always the same for all players while the server is up.

My third attempt was trying to move the choice generation into the `def creating_session(subsession)` function so that it would run every time a new session is created:

```
def creating_session(subsession):
    import random      
    loaded_dataset = loadDataSet(r'courses.xlsx')
    choices_list = []
    for p in subsession.get_players():
        random_sets = generateSelection(loaded_dataset, 4)
        testchoices = []
        for set in random_sets:
            choice = [str(set["id"]) , set["data"][0]] 
            testchoices.append(choice)
        p.coursestest.choices = testchoices 
```

This also doesn't work because the `coursestest` field isn't yet available.

How can I accomplish this?

**Comment by oTree-org** [comment]
In creating_session, generate random choices for each player and store it in a participant field. Then FIELD_choices should return the value of that participant field.

**Comment by aderiyeva** [comment]
Thanks a lot, it helped!
