### ISSUE TITLE
Order players by label/participant label

### ISSUE THREAD

**Issue by somas95** [oTree-org/oTree#115]
Right now the important bit in games is the participant. If you have a gender distribution in a lab you can assign a specific url to each computer, but what will matter when specifying variables to each participant will be in what order they connect to the server because that order will be used for assigning a player id. It would be desirable either being able to sort participants (like on ztree) or at least to be able to link participant and players somehow, so the order of connection does not matter but the participant id of each one

**Comment by oTree-org** [comment]
see here: https://otree.readthedocs.io/en/latest/rooms.html#pre-assigning-participants-to-labels

**Comment by somas95** [comment]
This is just what I needed, and didn't know it was a thing. Thanks!
