### ISSUE TITLE
Dynamic Timeouts

### ISSUE THREAD

**Issue by benarito** [oTree-org/oTree#47]
Am trying to allow users to input on the time they wish to perform a give task, and this is the value i want to base the timeouts on. 

Is it currently possible and if yes, how can I go about it.

Thanks,

**Comment by oTree-org** [comment]
You can define `timeout_seconds` as a property, using `@property`. (This is not official API, just try it out and see if it works.)

**Comment by oTree-org** [comment]
For example:

```
@property
def timeout_seconds(self):
    return self.player.desired_time_limit
```

**Comment by benarito** [comment]
Great. Thanks Chris.
