### ISSUE TITLE
Debug = False breaks jQuery

### ISSUE THREAD

**Issue by NoahGrumman** [oTree-org/oTree#49]
Setting DEBUG = False in Settings.py breaks jQuery and makes all pages be displayed without CSS. The following is logged to the console: 

```
Uncaught ReferenceError: $ is not defined
```

When DEBUG = True, the following is included in the HTML that is generated:
```
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- compiled and minified CSS -->
<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-theme.min.css">

<link rel="stylesheet" href="/static/otree/css/theme.css">
<link rel="stylesheet" href="/static/otree/katex/katex.min.css">

<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
<script>window.jQuery || document.write('<script src="/static/otree/js/jquery.min.js">\x3C/script>')</script>
```

However, these lines are not included when DEBUG = False. I assume this is where the problem lies.

It could also be user error as I just started using oTree.

**Comment by oTree-org** [comment]
already being tracked by https://github.com/oTree-org/otree-core/issues/406
