### ISSUE TITLE
Instructions Title

### ISSUE THREAD

**Issue by cataclysmic** [oTree-org/oTree#50]
Hey there,

is there a way to adapt the _templates/global/Instructions.html title?
I just rewrote it to the German term but would it be possible to make it language dynamic and substitutable to include ,e.g. , the player type.

Something like: "Instructions for worker" ; "Instructions for employer"

Thank you in advance.

**Comment by oTree-org** [comment]
You can use Django's `{% blocktrans %}` or `{% trans %}` tags. 
Or in the Python file you can use `ugettext`.

http://otree.readthedocs.org/en/latest/localization.html#writing-your-app-in-multiple-languages
https://docs.djangoproject.com/en/1.8/topics/i18n/translation/

By the way, you can sign up for our mailing list if you want: https://groups.google.com/forum/#!forum/otree
