### ISSUE TITLE
Umlauts (üöä) in survey replies not accepted as answers

### ISSUE THREAD

**Issue by cataclysmic** [oTree-org/oTree#51]
We have several survey questions with answers (radio buttons) containing German Umlauts.
When trying to submit such an answer I get an error saying that this is unacceptable answer.

![umlauts](https://cloud.githubusercontent.com/assets/4928443/12231620/45bed352-b859-11e5-9143-3247e6c61971.png)

Any idea how to solve this issue or where it might come from?

**Comment by oTree-org** [comment]
Can you post your code or send to chris@otree.org?

**Comment by oTree-org** [comment]
Fix is to use unicode strings prefixed with u (e.g. u"von hüchster")

**Comment by oTree-org** [comment]
Added a note in the docs: http://otree.readthedocs.org/en/latest/forms.html#user-input-validation
