### ISSUE TITLE
two people simultaneously pressing a button

### ISSUE THREAD

**Issue by falafellover** [oTree-org/oTree#54]
Hey O-tree enthusiasts, 

I am wondering if the following issue could be solved in oTree: I would like **two people** (on two different computers) **to press a button at the same time**. For example on both computers a counter is counting down 3, 2, 1 and then they have to press SPACE in a matter of half a second or so, thus implementing a joint action which hopefully has an effect on a public goods game afterwards. 
**Any way this is feasible?** Coming from z-Tree, we were running into difficulties programming such an event, and we hope that oTree offers more freedom into programming. 

I hope this is the right place to ask such questions. 

Best, 

Max

**Comment by oTree-org** [comment]
Hi, you can try asking the question here: https://groups.google.com/forum/#!forum/otree
