### ISSUE TITLE
Travis Build failing

### ISSUE THREAD

**Issue by mrtukkin** [oTree-org/oTree#57]
The Travis-CI build is failing with a pretty clear but also pretty meaningless error:

> Cannot import otree settings.
> Please make sure that you are in the root directory of your oTree project. This directory contains a settings.py and a manage.py file.

Which of course is wrong as both files are present..
Travis throws the same error since build [#210](https://travis-ci.org/oTree-org/oTree/builds/168641427).

[Diff](https://github.com/oTree-org/oTree/compare/80008acd1921...2d29537bc29e) tells me there was the change from 2.7 to 3.5, which seems unrelated but maybe it is.

Is the error somehow fixable? We would like to have some CI in out pipeline.

Best,
Maurice

**Comment by oTree-org** [comment]
Yes I noticed that also. But not sure how to fix :(

**Comment by mrtukkin** [comment]
Closed for me as #58 fixed it.
