### ISSUE TITLE
Missing Files?

### ISSUE THREAD

**Issue by ColbyCell** [oTree-org/oTree#59]
I just reinstalled this and noticed some missing files that were there when I was experimenting with oTree last spring: Dockerfile, dockerignore, entrypoint.sh, pg_ping.py, and runtime.txt. I'm new to this, but working from your documentation wouldn't a user at least need that Dockerfile to work with Docker Hub?

**Comment by oTree-org** [comment]
otree-docker is a separate repo. See here:

https://github.com/oTree-org/otree-docker
http://otree.readthedocs.io/en/latest/server/dockerhub.html
http://otree.readthedocs.io/en/latest/server/install-docker-adhoc.html
