### ISSUE TITLE
How to publish a seaborn graph through O-tree

### ISSUE THREAD

**Issue by jealdana** [oTree-org/oTree#61]
Hi!

I'm using this amazing solution for experimental games! It's awesome! Yet, I'll need help to import matplotlib and [SeaBorn categorical data plot library](seaborn.pydata.org/examples/scatterplot_categorical.html), in particular,  as a feedback the experiment rather than HighChart (Which is really nice to work with but so far needs js and I have not much experience with that yet :-) ).

Again thanks for creating this solution and thanks in advance!

**Comment by leliel12** [comment]
Seaborn is only a layer over matplotlib. So check how to implement
matplolib and django

**Comment by jealdana** [comment]
Thanks for the advice! I'll check that out! Best regards and have a great day!
