### ISSUE TITLE
[bug report]  The table in the Monitor page : cells got wrong header.

### ISSUE THREAD

**Issue by itsaquestion** [oTree-org/oTree#63]
![error](https://user-images.githubusercontent.com/7275202/38170318-14ee4ec0-35b5-11e8-911d-9058a67931b2.png)

System Info: 
oTree 2.0.29
Python 3.5.2
Ubuntu 16.04.3

**Comment by oTree-org** [comment]
I believe this is specific to python 3.5. Python 3.6 should not have this issue. I will think about a fix.
