### ISSUE TITLE
Questions about “chat” feature

### ISSUE THREAD

**Issue by wfc1994** [oTree-org/oTree#66]
Regarding chat, I noticed the one-to-one dialogue between the player and the player in the given example, with multiple chat boxes.
![image](https://user-images.githubusercontent.com/26211896/48174773-4d5caa80-e344-11e8-8ffa-3c0734f1949c.png)

I would like to ask if you can submit different channels of chat with different buttons. Equivalent to just doing a chat box, if so, how should I modify it? Thanks

**Comment by oTree-org** [comment]
Interesting idea but that's not supported.
