### ISSUE TITLE
Typo on Otree tutorial Part 3

### ISSUE THREAD

**Issue by NhatLg** [oTree-org/oTree#69]
There's a typo in the code under: class Group(BaseGroup):
https://otree.readthedocs.io/en/latest/tutorial/part3.ht
```
We also define a method called sent_back_amount_choices to populate the dropdown menu dynamically. This is the feature called {field_name}_choices, which is explained here: Dynamic form field validation.

def sent_back_amount_choices(self):
    return currency_range(
        c(0),
        self.group.sent_amount * Constants.multiplication_factor,
        c(1)
    )
```
It should be self.sent_amount instead of self.group.sent_amount because we calling attributes sent_amount of the instance of class Group()? I tested it using Python 3.7 and the newest Otree version 2.5.5

**Comment by oTree-org** [comment]
Yes you are right! I fixed it locally, thank you.
