### ISSUE TITLE
[feature request] Screenshots via `browser_bots`

### ISSUE THREAD

**Issue by lfaucheux** [oTree-org/oTree#70]
In experimental economics, at least in academic research when writing papers, it is *increasingly mandatory* to provide (in appendix) all the screenshots of the steps of an experiment.

Don't you think that it would be good to be able to do so via, say, `browser_bots`, passing something like `--with-screenshots=1`, (set to `0` by default) focusing on the first player's tab ?

**Comment by oTree-org** [comment]
Thank you for the suggestion. I agree it would be great to have but I think this would require re-architecting how the browser bots system works. Anyway I will keep it in mind for the future.
