### ISSUE TITLE
Defining a room via the web interface

### ISSUE THREAD

**Issue by Clashsoft** [oTree-org/oTree#73]
Defining a room / participant labels via the participant_label_file is cumbersome, because every time we have a new session, we have to update the software (hardcoding). It should be possible to create a room via the web interface.

Our specific use case:

We are running an online experiment where we send out the room links a few minutes before it starts. We used to send the same links for every session, but today we ran into a student who used the link he got from an older session to get into one where he was not invited. Luckily they did not participate twice, but it's a possibility with our link system.

**Comment by oTree-org** [comment]
Hi, can you describe your use case more? If you are using a different room for every session, you may be better off not using rooms at all. Instead you can to use the session-wide link which is different for every session, and append a participant_label to each URL.

I see your point about not wanting to update the files for every change, but on the other hand if you do it in the web interface, your changes will be lost when you reset the database.

**Comment by Clashsoft** [comment]
We used the session links before, but they were no good. We invited 28 people, created a session with 25 participants, 4 people didn't show up, and the experiment did not work any more. The room system allows us to know how many actually show up and create a session accordingly.

**Comment by oTree-org** [comment]
My suggestion is either to create many rooms in advance, even if you're not sure if you will use them.

If you need to dynamically change the participant_label_file, you could make your own Django view that modifies that file: https://otree.readthedocs.io/en/latest/misc/django.html#adding-custom-pages-urls

I don't want to store rooms and participant labels in the database because of the complexity that brings as well as the issue already mentioned. But if you have another suggestion I'm open to it.

**Comment by Clashsoft** [comment]
What about including the date or a custom value in the secure_urls hash? That could also solve the problem of being able to access the links later, but retains the actual labels.

**Comment by oTree-org** [comment]
Can you describe in more detail?

**Comment by Clashsoft** [comment]
Well the secure_urls hash ist constant (I guess it's based on the participant label?). But if there was a way to include a salt of sorts that can be set in the room view, we could invalidate old links. The salt could be any string.

**Comment by Clashsoft** [comment]
Another option would be to include the current date in the hash calculation. That would require no additional data to be stored (no field in the room view) but it's less flexible. Also, it doesn't work if one has two sessions in one day.

**Comment by oTree-org** [comment]
It's a good idea but I prefer to keep the design as simple as possible. I would not want to invalidate room links based on date, because the main purpose of rooms is to provide persistent links that can be used for multiple sessions.
