### ISSUE TITLE
404 Not Found /room/<room-name>

### ISSUE THREAD

**Issue by Clashsoft** [oTree-org/oTree#74]
otree v3.0.3.

When launching a session from a room, anyone who is extra gets redirected to a `404 Not found` page. Previously, the page said something along the lines of "The maximum number of participants for this session was reached", but that is no longer the case.

**Comment by Clashsoft** [comment]
I found this message in debug mode:

![image](https://user-images.githubusercontent.com/4145923/88155206-14439700-cc08-11ea-8376-6f9753d7b7be.png)

**Comment by oTree-org** [comment]
The message is still there near the bottom of the page. Anyway I will look soon to see if this is the correct approach.

**Comment by Clashsoft** [comment]
What do you mean by "near the bottom of the page"? This is all thats visible in prod mode:

![image](https://user-images.githubusercontent.com/4145923/88156910-62599a00-cc0a-11ea-897b-894c3ec54ded.png)

The page html is nothing more than:

```html
<h1>Not Found</h1><p>The requested resource was not found on this server.</p>
```

**Comment by oTree-org** [comment]
Ok I will take a look.

**Comment by Clashsoft** [comment]
Thank you! While you're at it, is there a chance the "maximum number of participants exceeded" message could be customizable? I was thinking about customizing the 404 page now that it's here, but couldn't find a way to do that.

**Comment by oTree-org** [comment]
Thanks for the suggestion. Out of curiosity, what do you want it to say?

**Comment by Clashsoft** [comment]
In our case, we want to instruct students to send an email with their paypal info to an email address, so we can pay them as extras.

**Comment by oTree-org** [comment]
Fixed the issue with the 404; as for making it customizable, I have put that in my list of features to consider for the next milestone, thanks.
