### ISSUE TITLE
自定义数据导出的一些BUG或建议

### ISSUE THREAD

**Issue by zangguojun** [oTree-org/oTree#91]
在`model.py`下设置了
```
def custom_export(players):
    yield ['session', 'participant_code', 'round_number', 'id_in_group', 'payoff']
    for p in players:
        yield [p.session.code, p.participant.code, p.round_number, p.id_in_group, p.payoff]
```
后在[http://localhost:8000/export/](http://localhost:8000/export/)中只能实现在`Per-app`中实现自定义导出，但是在`All apps`中却无法实现。
我想在`All apps`中实现这个功能时很重要的。
还有就是在`custom_export`函数中只能实现`yield`+需要的数据项，最好这里能添加另外一个功能：`yield`+不需要的数据项，就像Django的视图函数那样。

**Comment by oTree-org** [comment]
Sorry, i don't know Chinese and tried translating with google translate but still don't understand.
I don't have any current plans to make custom export for the "all apps" view. It's a nice concept but not straightforward to design.

**Comment by zangguojun** [comment]
好的 我知道了  谢谢
