### ISSUE TITLE
Project deployment issues

### ISSUE THREAD

**Issue by zangguojun** [oTree-org/oTree#95]
When I sign _otree_ above _Heroku_ ,it has no problem.
But When I sign _otree_ above _my own server_ ,it has lots of problems.
like:
`
TemplateSyntaxError: Unrecognised filter name 'fill' (line 19, in "forloop.counter|fill")
`
But I have clearly defined filter _fill_ ,and it didn't make any mistakes in Heroku

next:
`
Exception: Field "choice" uses a radio/select widget but no choices are defined
`
But I clearly defined the default value of _choice_ ,and it didn't make any mistakes in Heroku

It's really strange.

**Comment by oTree-org** [comment]
Make sure your Heroku server is using the same version of otree as locally.
